name = "DJUICE"
uuid = "1cb5fe60-6b70-416b-9050-039c23a62a10"
authors = ["Mathieu Morlighem <Mathieu.Morlighem@dartmouth.edu>", "Gong Cheng <gong.cheng@dartmouth.edu>"]
version = "0.1.0"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Triangulate = "f7e6ffb2-c36d-4f8f-a77e-16e897189344"

[compat]
ColorSchemes = "3.25"
Enzyme = "0.12"
Flux = "0.14"
GLMakie = "0.10"
MAT = "0.10"
SparseArrays = "1.8.0"
StatsBase = "0.34"
Triangulate = "2.3"
julia = "1.8"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
